### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by vlad0x00**
Fixed tmp dir path and made slider values deterministic.

### CODE REVIEW

**Comment by schutzekatze** [comment]
meteorflux.js commit also contains some spacing changes, which were automatically made by my editor. It seems to have just removed redundant spaces.

**Comment by schutzekatze** [comment]
Also, I should clarify what I mean by "Make slider values deterministic". Before the change, every time you move the slider to the max, it got a random value close to the max. This was because in slider change callback, the slider html element was first retrieved and then its value read, but it seems that this is not in sync with UI so it wasn't accurate. What I did, instead, was read the value from the callback UI parameter, which is the changed html element, and it now works well.

**Comment by schutzekatze** [comment]
Closing the request, as the new changs are being merged to a different repo (https://github.com/petnica-meteor-group/meteor-flux).

**Comment by vlad0x00** [comment]
Closing the pull request, as the new changes are being merged to a new repo (https://github.com/petnica-meteor-group/meteor-flux).

**Pull request closed without merging**
